# Generated by Django 4.1.7 on 2023-03-18 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_compare_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descritption',
            new_name='description',
        ),
    ]
